### PR TITLE
Add String to Integer solution

### LINKED ISSUE #11: Add String to integer (atoi)
Implement atoi which converts a string to an integer.

The function first discards as many whitespace characters as necessary until the first non-whitespace character is found. Then, starting from this character, takes an optional initial plus or minus sign followed by as many numerical digits as possible, and interprets them as a numerical value.

The string can contain additional characters after those that form the integral number, which are ignored and have no effect on the behavior of this function.

If the first sequence of non-whitespace characters in str is not a valid integral number, or if no such sequence exists because either str is empty or it contains only whitespace characters, no conversion is performed.

If no valid conversion could be performed, a zero value is returned.

**Note**:

- Only the space character ' ' is considered as whitespace character.

- Assume we are dealing with an environment which could only store integers within the 32-bit signed integer range: [−2<sup>31</sup>,  2<sup>31</sup> − 1]. If the numerical value is out of the range of representable values, INT_MAX (2<sup>31</sup> − 1) or INT_MIN (−2<sup>31</sup>) is returned.

**Example 1:**
> Input: 42
> Ouput: 42

**Example 2:**
> Input: "    -42"
> Output:  -42
> Explanation: The first non-whitespace character is '-', which is the minus sign. Then take as many numerical digits as possible, which gets 42.

**Example 3:**
> Input: "4193 with words"
> Output: 4193
> Explanation: Conversion stops at digit '3' as the next character is not a numerical digit.

**Example 4:**
> Input: "words and 987"
> Output : 0
> Explanation: The first non-whitespace character is 'w', which is not a numerical digit or a +/- sign. Therefore no valid conversion could be performed.

**Example 5:**
> Input : "-91283472332"
> Output: -2147483648
> Explanation: The number "-91283472332" is out of the range of a 32-bit signed integer. Therefore INT_MIN (−2<sup>31</sup>) is returned.

### PR DESCRIPTION
**Pull request by therohanjaiswal**
Closes #11

### CODE REVIEW

**Comment by dexterpuru** [comment]
Please have a look at this PR, you will need to submit the solution in this format, https://github.com/dexterpuru/leetcode_java/pull/17
look at the file changes to see the file structure.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@therohanjaiswal  Kindly name the folder the exact name given on Leetcode for the problem statement **excluding the problem number**. Also, the **main()** method is not necessary for the code. I'll further suggest **from next time** you create a branch from master and work on that branch and then create a pull request, as that is the traditional workflow of Git.

**Comment by therohanjaiswal** [comment]
I updated the files. Please verify.

**Review by YourAKShaw — APPROVED** [review]

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@therohanjaiswal Kindly follow the contribution guidelines. You need to add **only one problem solution and README.md per pull request**. I'll advise you to revert the changes you just made, and make a new branch and work on that branch and make a pull request from that branch. _P.S.: Patience is key._

**Review by YourAKShaw — APPROVED** [review]
**LGTM!**

You can move on to another issue while you wait. Remember, create an issue for a problem and ask for assignment. On assigning, get to it. Create a branch, work on that branch and make a pull request from that branch. Also, you can ask any questions if you need to.

**Comment by dexterpuru** [comment]
@therohanjaiswal Great job so far, only thing left is you need to put link of related issue in PR description.

**Comment by YourAKShaw** [comment]
@therohanjaiswal To link PR with issue, simply type a '#' and the issue number and select the issue from the drop down.

**Comment by dexterpuru** [comment]
@therohanjaiswal you deleted all your work in last commit, please fix that.

**Comment by YourAKShaw** [comment]
@dexterpuru He actually added the solution to two different problems earlier. So he kinda deleted the solution to the second problem.

**Comment by dexterpuru** [comment]
@Ak-Shaw ohh thats what it is, sorry my bad,

**Review by dexterpuru — APPROVED** [review]

**Pull request merged**
