### PR TITLE
Added CONTRIBUTING.md and problemStatementList.md and edited README.md

### PR DESCRIPTION
**Pull request by YourAKShaw**

### CODE REVIEW

**Review by dexterpuru — CHANGES_REQUESTED** [review]
Awesome work, i think we should also 
- mention that every issue should have link of that question in its description
- Add format for PRs, (it need title as question name and it must have a issue link in description)

**Comment by YourAKShaw** [comment]
I made the necessary changes. Further, after the merge, I'll create issue and PR templates for the aforementioned needs.

**Review by dexterpuru — APPROVED** [review]
Great job, this look nice 💯

**Comment by dexterpuru** [comment]
> 
> 
> I made the necessary changes. Further, after the merge, I'll create issue and PR templates for the aforementioned needs.

That sounds awesome!!!

**Pull request merged**
