### PR TITLE
Group Anagrams

### PR DESCRIPTION
**Pull request by MayankSingh173**
https://github.com/dexterpuru/leetcode_java/issues/6

### CODE REVIEW

**Comment by dexterpuru** [comment]
@MayankSingh173 please make issue first, then after i assign the issue to you, then make the PR.
1. Add question link to issue description
2. After creating issue, edit this PR and put link of that issue in the PR description
You should refer to currently opened issue to check the format,
Please read the README to understand the procedure of contribution.

**Comment by MayankSingh173** [comment]
@dexterpuru Heyy I'm new open source..Could you please help me how to make an issue.

**Comment by dexterpuru** [comment]
@MayankSingh173 sure,

1. Go here:- https://github.com/dexterpuru/leetcode_java/issues/new
2. Put question in title
3. Put link to question in description
4. If you want that issue to be assigned to yourself, write it at the end.
5. After that i will assign that issue to you(if you wanted) and then you could open PR.
6. PR title should have question as title and its description must have link of the Issue that you created in step 1.

**Comment by dexterpuru** [comment]
You don't need to close the PR, just make a issue, and after i assign that issue to you, edit the PR description and put the link of issue in it.

**Comment by MayankSingh173** [comment]
Sorry...I closed the PR...I'll make a new PR

**Comment by MayankSingh173** [comment]
I made an issue..can you please assign it me

**Comment by MayankSingh173** [comment]
I add the necessary changes in the PR...Is it fine?

**Comment by dexterpuru** [comment]
Awesome work so far @MayankSingh173 
I have only 3 requests:- 

1. Rename Question.txt to README.md
2. Rename Solution.txt to Solution.java
3. Move the Explanation of your approach from Question file to README.md.

**Comment by YourAKShaw** [comment]
@MayankSingh173 Kindly follow the instructions given by @dexterpuru 
Also, in the README.md for the problem statement, add problem link, problem statement and solution approach, in the the given order. You can check the other folders in the master branch of **dexterpuru/leetcode_java** for reference.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@MayankSingh173 Kindly make the necessary changes.

**Comment by MayankSingh173** [comment]
Heyy @Ak-Shaw ....I kind of busy today...I'll make the necessary changes by tomorrow....Is it fine?.

**Comment by YourAKShaw** [comment]
Sure, take your time.

**Comment by MayankSingh173** [comment]
Heyy @dexterpuru @Ak-Shaw ...I'm new to git and github...Can you please help me how should I add README.md file. I made that file in my pc.

**Comment by MayankSingh173** [comment]
I made an another PR...Please let me know If am doing in a right way.

**Pull request closed without merging**
