### PR TITLE
Best time to buy and sell stock

### PR DESCRIPTION
**Pull request by ushachengan**
PR for https://github.com/dexterpuru/leetcode_java/issues/41

### CODE REVIEW

**Review by dexterpuru — APPROVED** [review]

**Comment by dexterpuru** [comment]
@ushachengan awesome work, code is really good, can you please shift this problem to arrays folders, because this is not much of a DP problem, the one with cool-down could be really good example for DP.

**Comment by ushachengan** [comment]
@dexterpuru moved the code inside Array folder. thanks

**Review by YourAKShaw — APPROVED** [review]
@ushachengan  All good. I have just one tiny request though, always name the folder exactly the name given on Leetcode excluding the problem number. In this case, don't exclude the spaces in between. Kindly keep that in mind from next time.

**Comment by ushachengan** [comment]
sure @Ak-Shaw , I will follow that and fix this folder name in my next PR as well.

**Comment by YourAKShaw** [comment]
@ushachengan I've fixed the name of the solution folder from this PR. Just keep that in mind from next time. 😄👍
Also, whenever working on your local setup, sync your forked version of the repo with the original. It'll help a lot.

**Pull request merged**
