### PR TITLE
Adding solution for 'Group Anagrams' problem

### LINKED ISSUE #6: Group Anagram
https://leetcode.com/problems/group-anagrams/

### PR DESCRIPTION
**Pull request by MayankSingh173**
## Closes #6

### CODE REVIEW

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
Kindly add Time and space complexity analysis in README.md.

**Comment by MayankSingh173** [comment]
I updated the README.md file....Kindly have a look and let me know If I need to update anything.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
Replace line no. 25 of README.md with `1 <= strs.length <= 10<sup>4</sup>`. Also, add the problem name in list_of_questions.txt

**Comment by MayankSingh173** [comment]
Done...Kindly Review

**Comment by YourAKShaw** [comment]
Add the problem name in list_of_questions.txt **IN THIS PR**.

**Comment by MayankSingh173** [comment]
Done...I did in the right way??

**Review by YourAKShaw — APPROVED** [review]
Yup! Good Job!! :rocket:

**Comment by MayankSingh173** [comment]
Thanks for guiding me.  This is the first time I'm doing open source contributions. I learned the power of git and GitHub.

**Comment by YourAKShaw** [comment]
@MayankSingh173 Sure man! _Open source is all about collaboration and community._

**Pull request merged**
