### PR TITLE
Added Detect Capital Problem

### PR DESCRIPTION
**Pull request by PrinceKhatick**
Done, please review it and merge.

### CODE REVIEW

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@PrinceKhatick I've got two requests:
- You're using methods like equals() and substring(), so kindly correct the time complexity. Also you need to specify the space complexity too. And give reasons for both.
- Also, add the name of the problem statement in list_of_questions.txt

**Comment by PrinceKhatick** [comment]
> @PrinceKhatick I've got two requests:
> 
> * You're using methods like equals() and substring(), so kindly correct the time complexity. Also you need to specify the space complexity too. And give reasons for both.
> * Also, add the name of the problem statement in list_of_questions.txt

Will be doing that sure, Thanks for informing

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@PrinceKhatick Actually the space complexity will be of O(N) because of the variables s1, s2 and s4 which creates a new string of length N each time. Kindly change that.

**Comment by PrinceKhatick** [comment]
> @PrinceKhatick Actually the space complexity will be of O(N) because of the variables s1, s2 and s4 which creates a new string of length N each time. Kindly change that.

Ok doing that and sending

**Review by YourAKShaw — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
