### PR TITLE
added solution and README.md for 'Add Two Numbers' problem

### LINKED ISSUE #13: Add solution for Add Two Numbers problem
**https://leetcode.com/problems/add-two-numbers/**

I'd like to work on this issue. Kindly assign it to me.

### PR DESCRIPTION
**Pull request by YourAKShaw**
## Closes #13

### CODE REVIEW

**Comment by dexterpuru** [comment]
Awesome work, keep it up!!

**Comment by dexterpuru** [comment]
please add the question in list_of_question.txt file also.

**Comment by YourAKShaw** [comment]
Sure.

**Comment by dexterpuru** [comment]
One more thing this is appreciated in open source, whenever your code is merged in main branch, like what happened in this PR, you should delete the branch from your fork. (It is not necessary, but its one of those good practices).

**Comment by YourAKShaw** [comment]
Sure. Thanks.

**Pull request merged**
