### PR TITLE
Longest Substring without repeating characters solution

### PR DESCRIPTION
**Pull request by therohanjaiswal**
Fix issue #10

### CODE REVIEW

**Comment by YourAKShaw** [comment]
@therohanjaiswal Kindly refrain from working on the master branch. **It'll be in best interest if from next time you create a new branch, work on that branch and create a pull request from that branch**.

**Review by YourAKShaw — APPROVED** [review]

**Comment by YourAKShaw** [comment]
@therohanjaiswal While you wait, you can create a new issue and get going. :rocket:

**Comment by therohanjaiswal** [comment]
@Ak-Shaw Ok. I Will work on a new branch next time.

**Review by dexterpuru — APPROVED** [review]

**Comment by dexterpuru** [comment]
@therohanjaiswal great job 👍

**Pull request merged**
