### PR TITLE
[issue #23] evaluate division

### PR DESCRIPTION
**Pull request by rusyasoft**
solution for issue #23

### CODE REVIEW

**Comment by dexterpuru** [comment]
@rusyasoft everything is good, but there is a conflict in questions file, I have resolved the same in your last 2-3 PRs, now you will have to take care of it. @Ak-Shaw please guide @rusyasoft

**Comment by rusyasoft** [comment]
@dexterpuru can you check it now? I have tried to fix it by myself. 
I got pull from your last master and commited with my last update

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@rusyasoft Kindly **_checkout the list_of_questions.txt file in the upstream/master_**. To ensure that you have no merge conflicts for the moment, you can _copy all that is there in the list_of_questions.txt file in the upstream/master and then add the name of your problem statement at the end_. That'll do it.

**Comment by rusyasoft** [comment]
@Ak-Shaw check it now please

**Review by YourAKShaw — APPROVED** [review]
@rusyasoft Nice work.

**Pull request merged**
