### PR TITLE
Rotate Image

### PR DESCRIPTION
**Pull request by Zaman3027**
https://github.com/dexterpuru/leetcode_java/issues/46

### CODE REVIEW

**Comment by dexterpuru** [comment]
@Zaman3027 great job so far, but you will need to make individual PRs for every question and also put the link of related issue in PR. I know it sounds silly but we need to keep the guidelines and the procedure straight, so please make appropriate changes.

**Comment by Zaman3027** [comment]
Done

**Comment by Zaman3027** [comment]
https://github.com/dexterpuru/leetcode_java/issues/46
Done

**Comment by dexterpuru** [comment]
Now your solution is getting compilation error, please look into it.
Screenshot (175)

**Comment by Zaman3027** [comment]
This was java solution you have complied in cpp
please check.

**Review by YourAKShaw — CHANGES_REQUESTED** [review]
@Zaman3027 I checked your code. It works. I have a request though. Kindly add a couple of comments in Solution.java to explain the methods.

**Comment by Zaman3027** [comment]
Added comment.

**Review by YourAKShaw — APPROVED** [review]

**Comment by Zaman3027** [comment]
Can you you labels it hacktober-accepted?

**Comment by YourAKShaw** [comment]
It actually doesn't need to be, because according to the new rules of hacktoberfest a valid PR is one which is either merged, approved or marked as hacktoberfest-accepted. Anyways, if it makes you feel better, then why not.

**Pull request merged**
